// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SixB_Api.Migrations
{
    [DbContext(typeof(BookingDataContext))]
    [Migration("20220531121354_V001")]
    partial class V001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BookingDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flexibility")
                        .HasColumnType("int");

                    b.Property<int>("VehicleSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Booking");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a21a6ed-fd98-44cf-ab03-f64bf55b100a"),
                            Approved = false,
                            BookingDate = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "913336296",
                            CreatedOn = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "marcus.carreira@gmail.com",
                            Flexibility = 1,
                            VehicleSize = 1
                        },
                        new
                        {
                            Id = new Guid("1c11a6ed-fd98-44cf-ab03-f64bf55b100b"),
                            Approved = false,
                            BookingDate = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "913336296",
                            CreatedOn = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "fabricedomingues7@gmail.com",
                            Flexibility = 1,
                            VehicleSize = 4
                        },
                        new
                        {
                            Id = new Guid("1a44a6ed-fd98-44cf-ab03-f64bf55b100b"),
                            Approved = false,
                            BookingDate = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "913336296",
                            CreatedOn = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jack@javeloper.co.uk",
                            Flexibility = 1,
                            VehicleSize = 1
                        },
                        new
                        {
                            Id = new Guid("0ac2a6ed-fd98-44cf-ab03-f64bf55b100b"),
                            Approved = false,
                            BookingDate = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "913336296",
                            CreatedOn = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "josh@joshwalshaw.com",
                            Flexibility = 3,
                            VehicleSize = 3
                        },
                        new
                        {
                            Id = new Guid("0ac2a6ed-ab12-44cf-ab03-f64bf55b100b"),
                            Approved = false,
                            BookingDate = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "913336296",
                            CreatedOn = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "angelo@6bdigital.com",
                            Flexibility = 2,
                            VehicleSize = 1
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e60a6ed-fd98-44cf-ab03-f64bf55b210a"),
                            Login = "marcus.carreira@gmail.com",
                            Name = "Marcus Vinícius Carreira Dorbação",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("1a60a6ed-fd98-44cf-ab03-f64bf55b210a"),
                            Login = "fabricedomingues7@gmail.com",
                            Name = "Fabrice Domingues",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("1a40a6ed-fd98-44cf-ab03-f64bf55b100a"),
                            Login = "jack@javeloper.co.uk",
                            Name = "Jack",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("1b41a6ed-fd98-44cf-ab03-f64bf55b100a"),
                            Login = "josh@joshwalshaw.com",
                            Name = "Josh",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("0a41a6ab-fd98-44cf-ab03-f64bf55b100a"),
                            Login = "angelo@6bdigital.com",
                            Name = "Angelo",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
