// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SixB_Api.Migrations
{
    [DbContext(typeof(BookingDataContext))]
    [Migration("20220531104129_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e60a6ed-fd98-44cf-ab03-f64bf55b210a"),
                            Login = "marcus.carreira@gmail.com",
                            Name = "Marcus Vinícius Carreira Dorbação",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("1a60a6ed-fd98-44cf-ab03-f64bf55b210a"),
                            Login = "fabricedomingues7@gmail.com",
                            Name = "Fabrice Domingues",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("1a40a6ed-fd98-44cf-ab03-f64bf55b100a"),
                            Login = "jack@javeloper.co.uk",
                            Name = "Jack",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("1b41a6ed-fd98-44cf-ab03-f64bf55b100a"),
                            Login = "josh@joshwalshaw.com",
                            Name = "Josh",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        },
                        new
                        {
                            Id = new Guid("0a41a6ab-fd98-44cf-ab03-f64bf55b100a"),
                            Login = "angelo@6bdigital.com",
                            Name = "Angelo",
                            Password = "$2a$11$GO38rMrQhRQM0czSRZm2Oe.7J2JWe75a9.iuDiinGuWdaECA1G1Wy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
